# config.py
# Rewrite of commonConfig.py
# New: 7/26/25
#

# Many ambiguities: I'd -> I had or I would
#
simple_contractions = { 
"ain't": "am not",
"Ain't": "Am not",
"aren't": "are not",
"Aren't": "Are not",
"can't": "cannot",
"Can't": "Cannot",
"'cause": "because",
"'Cause": "Because",
"could've": "could have",
"Could've": "Could have",
"couldn't": "could not",
"Couldn't": "Could not",
"didn't": "did not",
"Didn't": "Did not",
"doesn't": "does not",
"Doesn't": "Does not",
"don't": "do not",
"Don't": "Do not",
"goin'": "going",
"Goin'": "Going",
"hadn't": "had not",
"Hadn't": "Had not",
"hasn't": "has not",
"Hasn't": "Has not",
"haven't": "have not",
"Haven't": "Have not",
"he'd": "he would, he had",     # would or had?
"He'd": "He would, He had",     # 
"he'll": "he will",
"He'll": "He will",
"he's": "he is",
"He's": "He is",
"how'd": "how would, how did",
"How'd": "How would, How did",
"how'd'y": "how do you",
"How'd'y": "How do you",
"how'll": "how will",
"How'll": "How will",
"how's": "how is",
"How's": "How is",
"i'd": "i would, i had",   # I'd (had) never bused so many dishes in one night
"I'd": "I would, I had",
"i'll": "i will",
"I'll": "I will",
"i'm": "i am",
"I'm": "I am",
"i've": "i have",
"I've": "I have",
"isn't": "is not",
"Isn't": "Is not",
"it'd": "it would, it had",
"It'd": "It would, It had",
"it'll": "it will",
"It'll": "It will",
"it's": "it is",
"It's": "It is",
"let's": "let us",
"Let's": "Let us",
"ma'am": "madam",
"Ma'am": "Madma",
"mayn't": "may not",
"Mayn't": "May not",
"might've": "might have",
"Might've": "Might have",
"mightn't": "might not",
"Mightn't": "Might not",
"must've": "must have",
"Must've": "Must have",
"mustn't": "must not",
"Mustn't": "Must not",
"needn't": "need not",
"Neddn't": "Need not",
"o'clock": "of the clock",
"O'clock": "Of the clock",
"oughtn't": "ought not",
"Oughtn't": "Ought not",
"shan't": "shall not",
"Shan't": "Shall not",
"sha'n't": "shall not",
"She'n't": "Shall not",
"she'd": "she would, she had",
"She'd": "She would, She had",
"she'll": "she will",
"She'll": "She will",
"she's": "she is, she has",
"She's": "She is, She has",
"should've": "should have",
"Should've": "Should have",
"shouldn't": "should not",
"Shouldn't": "Should not",
"so've": "so have",
"So've": "So have",
"so's": "so is",
"So's": "So is",
"that'd": "that would, that had",
"That'd": "That would, That had",
"that's": "that is",
"That's": "That is",
"there'd": "there would, there had",
"There'd": "There would, there had",
"there's": "there is",
"There's": "There is",
"they'd": "they would, they had",
"They'd": "They would, they had",
"they'll": "they will",
"They'll": "They will",
"they're": "they are",
"They're": "They are",
"they've": "they have",
"They've": "They have",
"to've": "to have",
"To've": "They have",
"wasn't": "was not",
"Wasn't": "Was not",
"we'd": "we would, we had",
"We'd": "We would, We had",
"we'll": "we will",
"We'll": "We will",
"we're": "we are",
"We're": "We are",
"we've": "we have",
"We've": "We have",
"weren't": "were not",
"Weren't": "Were not",
"what'll": "what will",
"What'll": "What will",
"what're": "what are",
"What're": "What are",
"what's": "what is",
"What's": "what is",
"what've": "what have",
"What've": "What have",
"when's": "when is",
"When's": "When is",
"when've": "when have",
"When've": "When have",
"where'd": "where would, where did",
"Where'd": "Where would, Where did",
"where's": "where is",
"Where's": "Where is",
"where've": "where have",
"Where've": "Where have",
"who'll": "who will",
"Who'll": "Who will",
"who's": "who is",
"Who's": "Who is",
"who've": "who have",
"Who've": "Who have",
"why's": "why is",
"Why's": "Why is",
"why've": "why have",
"Why've": "Why have",
"will've": "will have",
"Will've": "Will have",
"won't": "will not",
"Won't": "Will not",
"would've": "would have",
"Would've": "Would have",
"wouldn't": "would not",
"Wouldn't": "Would not",
"y'all": "you all",
"Y'all": "You all",
"you'd": "you would, you had",
"You'd": "You would, You had",
"you'll": "you will",
"You'll": "You will",
"you're": "you are",
"You're": "You are",
"you've": "you have",
"You've": "You have"
}


# Crude class for sentences
#
class inputSentence:

    def __init__(self, rawSent, taggedSent, data):
        self.rawSent    = rawSent
        self.taggedSent = taggedSent
        self.data       = data

    def printAll(self):
        print('rawSent:    ', self.rawSent)
        print('taggedSent: ', self.taggedSent)
        print('data:       ', self.data)

        
    


